name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    if: github.repository == 'ethlimo/ens-hooks'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2
        with:
          egress-policy: audit
      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@fda730cb152c05a849d6d84325e50c6182d9d1e9
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'