name: Unit Tests

on:
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'contracts/**'
      - 'ignition/**'
      - 'scripts/**'
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'package-lock.json'
      - 'hardhat.config.ts'
      - 'tsconfig.json'
    branches-ignore:
      - 'release-please--*'

jobs:
  tests:
    if: github.repository == 'ethlimo/ens-hooks'
    name: Test Suite
    environment: Development
    runs-on: ubuntu-latest
    steps:
        # step-security/harden-runner@v2.13.1
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
        with:
          egress-policy: audit
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443
            eth-mainnet.g.alchemy.com:443
      - name: Checkout the repo
        # actions/checkout@v5
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up Node.js 22.x
        # actions/setup-node@v5
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444       
        with:
          node-version: '22'
      - run: npm ci
      - run: npm test
        env:
          NODE_OPTIONS: --no-experimental-strip-types
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
